apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: three-tier
  labels:
    app: frontend
    role: frontend
spec:
  type: ClusterIP
  selector:
    role: frontend
  ports:
  - port: 3000
    name: http
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
